### ISSUE TITLE
Issue trying to run Passkit-Keys

### ISSUE THREAD

**Issue by jsnop** [walletpass/pass-js#539]
Hey folks, any help with this error would be amazing! 

Been trying to convert my .p12 into .pem. I get the error below. Here's what I've tried so far.

- Node Version is 15.11.0, npm install again just in case.
- Checked directory / file permissions, everything 777, still no success. 
- Project is currently running on WSL, tried running passkit-keys directly on windows too, no success.
- .p12 was generated by a workmate on his Mac, I work on windows / WSL. Could that be a reason?

Otherwise, I'm not really sure what to try / search for, my googles haven't really lead me anywhere concrete. Node is relatively new to me and Mac development too, double whammy.

Like I said, any help would be super appreciated. Thanks in advance.

```
Extracting Apple WWDR certificate into directory <DIRECTORY>
child_process.js:637
    throw err;
    ^

<ref *1> Error: spawnSync security ENOENT
    at Object.spawnSync (internal/child_process.js:1067:20)
    at spawnSync (child_process.js:602:24)
    at execFileSync (child_process.js:629:15)
    at Object.<anonymous> (<PATH>\node_modules\@walletpass\pass-js\bin\passkit-keys:34:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawnSync security',
  path: 'security',
  spawnargs: [
    'find-certificate',
    '-p',
    '-c',
    'Apple Worldwide Developer Relations Certification Authority'
  ],
  error: [Circular *1],
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}
```

**Comment by jsnop** [comment]
SOLVED > Colleague had to run it on his mac, not sure if it's because he generated the p12 or if passkit-keys only works on mac.
